---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
    - community.aws

  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/bastion-setup

    - name: Import VPC output Variable
      include_vars: vars/output_vars

    - name: Create vprofile EC2 key
      amazon.aws.ec2_key:
        name: vprofile-key
        region: "{{ region }}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: "0600"
      when: key_out.changed

    - name: Create Security Group for bastion host
      amazon.aws.ec2_security_group:
        name: Bastion-host-sg
        description: Allow port 22 from MYIP and all ports within SG
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_out

        - name: Creating Bastion Host
      amazon.aws.ec2_instance:
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}"
        wait: true
        wait_timeout: 300
        exact_count: 1
        filters:
          "tag:Name": "Bastion_host"
          "tag:Project": "Vprofile"
        tags:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        network:
          assign_public_ip: true
          vpc_subnet_id: "{{ pubsub1id }}"
          security_groups:
            - "{{ BastionSG_out.group_id }}"
      register: bastionHost_out

    - name: Show Bastion Host public IP
      debug:
        msg: "Bastion Host public IP: {{ bastionHost_out.instances[0].public_ip_address }}"

